### ISSUE TITLE
There should be a way to remove a Rich Description

### ISSUE THREAD

**Issue by SevenSpheres** [celestiamobile/celestia-addon-validator#1024]
From Discord:
> SevenSpheres: Problem with Kepler-61, the rich description wasn't updated. There should be a way to remove a rich description.
> lev: Please make an issue so I can remove manually.

**Comment by DaveBowman2001** [comment]
Submitted a new PR #1025 that removes the outdated RD from Kepler-61 with a new RD, but yeah there should be a way to remove a `Rich Description` if it is no longer needed

**Comment by levinli303** [comment]
I've added support for removing rich descriptions.

Please test with this checked:
<img width="387" alt="Screenshot 2023-10-31 at 22 32 47" src="https://github.com/celestiamobile/celestia-addon-validator/assets/17924287/302e81cb-e27d-4e02-8d9c-0f8d6a766761">
