### ISSUE TITLE
Addon submission no longer works correctly

### ISSUE THREAD

**Issue by SevenSpheres** [celestiamobile/celestia-addon-validator#1562]
The [addon submission form](https://celestia.mobi/submit-addon), signed in with GitHub, no longer shows a "Submit" button that creates a pull request. Instead, there's a "Generate" button which downloads a zip file. Presumably I could create a pull request adding this zip file to the `pending_zip` directory but I don't think this is the intended behavior.

**Comment by levinli303** [comment]
should be fixed by https://github.com/celestiamobile/celestia-mobi-content-localization/commit/bf19446dc4c1a827d46b36bc657526977e38796c
