### ISSUE TITLE
Addon Submission may not be Working Correctly

### ISSUE THREAD

**Issue by Karistus** [celestiamobile/celestia-addon-validator#1933]
The add-on submission website is having issues creating pull requests.

Using the GitHub sign-in the submission will remain stuck at the "creating Pull Request" stage, regardless of if a new add-on is being submitted, the size of the zip file attempting to be uploaded, or if the update is as simple as adjusting the description of an existing addon.

Attempting to use Apple ID gives and invalid error and mentions a missing STRING value

Attempting to use a direct submission gets it stuck at the Download ZIP file stage, and does not give a change ID. The ZIP file is still downloaded successfully however.

**Comment by DaveBowman2001** [comment]
In my case, this usually happens now when I am uploading or updating addons larger than 30 MB in size

**Comment by levinli303** [comment]
Using GitHub only: please go to your forked repo https://github.com/YOUR_GITHUB_USERNAME/celestia-addon-validator/ and delete your repo in the repo settings

Using Apple ID: CloudKit JS authentication is down https://forums.developer.apple.com/forums/thread/751408

Not using any: you are expected to update the zip manually in pending_zip folder

**Comment by Karistus** [comment]
Sorry, lev. I wasn't aware that i would need to refresh my repo every now an again. 

Thanks for your help though
